### PR TITLE
Added host and checkout feature to gegit #1

### PR DESCRIPTION
**Pull request by n1haldev**
The option to enter host and checkout has been added and is working.

### CODE REVIEW

**Comment by skudlur** [comment]
@n1haldev does it work now? can you send a screenshot?

**Comment by n1haldev** [comment]
image
As you can see a new directory named vinhal was cloned locally from the compiled binary.

**Comment by skudlur** [comment]
awesome!

**Comment by skudlur** [comment]
!bounty 80

**Pull request closed without merging**
