### PR TITLE
Added check for ssh setup

### PR DESCRIPTION
**Pull request by sujay1844**
Solves #2

### CODE REVIEW

**Comment by skudlur** [comment]
@sujay1844 LGTM but can you share a screenshot of an instance where the ssh is not configured and gegit shows the user that this happened?

**Comment by sujay1844** [comment]
SSH is setup for normal user, no error is displayed. But root user does not have SSH setup, so it shows an error along with a link to the relevant docs
image

**Comment by skudlur** [comment]
Awesome! Good to see another fedora user :)

**Comment by sujay1844** [comment]
the bounty? @skudlur

**Comment by skudlur** [comment]
!bounty 80

**Pull request merged**
